schema: spec-driven

# Contexto del proyecto
context: |
  Tech stack: Python 3.x, pygame (para la versión con GUI)
  Domain: CLI Juego (Legacy Mode)
  Description: Un juego de Tic Tac Toe (Gato) que se ejecuta totalmente en la terminal.
  Style: Programación procedimental o POO básica, hay una version basica por consola y una con interfaz grafica (pygame)
  Constraints: 
    - Solo usar caracteres ASCII o UNICODE para el tablero en la version por consola.
    - En la version con GUI, usar los estadares mas actualizados de pygame

# Reglas por artefacto
rules:
  proposal:
    - Definir claramente la estructura del tablero (ej. una lista de 9 elementos).
    - Explicar cómo se validarán las victorias (filas, columnas y diagonales).
  tasks:
    - Debe haber una separacion por carpetas entre la version por consola y la version con GUI
    - Ambas versiones con las practicas mas actualizadas de python 2026. 